baseURL = "https://muhammadmuazen-blog.pages.dev/"
defaultContentLanguage = "en"

# Automatically generate robots.txt
enableRobotsTXT = true
enableEmoji = true
languageCode = "en"
theme = "gokarna"
title = "Muhammad Muazen"

[params]
  # Description under the name
  description = "Cybersecurity engineer ğŸ¥· Offensive security ğŸ”“, defensive security ğŸ›¡ï¸. Proficient in C Â©ï¸/Python ğŸ/Rust ğŸ¦€ for tooling âš”ï¸/malware ğŸ‘¾. Experienced in Windows ğŸªŸ/Linux ğŸ§, network analysis ğŸ“¶ & attack simulation âš”ï¸â›Š. Team collaborator ğŸ¤, In Love with Low Level Programming and Embedded ğŸ“Ÿ, Books Worm ğŸ“š"
  # Social Links
  socialIcons = [
    {name = "github", url = "https://github.com/MuhammadMuazen"},
    {name = "linkedin", url = "https://www.linkedin.com/in/muhammad-muazen-42004a296/"},
    {name = "email", url = "mailto:muhammadmuazen@gmail.com"}
  ]
  # footer near the year
  footer = "Muhammad Muazen"
  # avatar picture
  avatarURL = "/images/avatar.jpg"
  # Display posts on the home page
  showPostsOnHomePage = "recent"
  numberPostsOnHomePage = 2
  # Favicons
  favicon = "favicons/favicon.ico"
  favicon16x16 = "favicons/favicon-16x16.png"
  favicon32x32 = "favicons/favicon-32x32.png"
  appleTouchIcon = "favicons/apple-touch-icon.png"
  androidChrome192 = "favicons/android-chrome-192x192.png"
  androidChrome512 = "favicons/android-chrome-512x512.png"
  webmanifest = "favicons/site.webmanifest"
  # Other configs
  displayReadingTime = true
  showBackToTopButton = true
  # Define SEO keywords
  metaKeywords = ["blog", "gokarna", "hugo", "cybersecurity", "hacking", "ethicalhacker", "penetration tester", "programming",
                   "c", "rust", "python", "cs", "computer science", "viral", "cyber", "tech", "IT", "computers", "ideas", "hustle",
                   "work", "job", "posts", "sharing", "information", "ctf", "defensive", "embedded", "arduino", "esp32", "stm32",
                   "raspberry pi", "hardware", "software", "hiring", "personal", "learning", "free", "opensource"]
  # Used to add the fonst I need to add the icons
  customHeadHTML = "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">"

[menu]
  # Home page
  [[menu.main]]
    name = "Home"
    pre = "<i class='fas fa-home'></i> "
    url = "/"
    weight = 1
  # IT Posts page
  [[menu.main]]
  name = "IT Posts"
  pre = "<i class='fa fa-code fa-fw'></i> "
  url = "/it-posts/"
  weight = 2
  # Non IT Posts page
  [[menu.main]]
  name = "Non-IT Posts"
  pre = "<i class='fa fa-book fa-fw'></i> "
  url = "/non-it-posts/"
  weight = 3
  # Services Page
  [[menu.main]]
  name = "Services"
  pre = "<i class='fas fa-briefcase fa-fw'></i> "
  url = "/services"
  weight = 4
  # About Me page
  [[menu.main]]
  name = "About Me"
  pre = "<i class='fa fa-user fa-fw'></i> "
  url = "/about-me/"
  weight = 5
  # Contacts page
  [[menu.main]]
  name = "Contact me"
  pre = "<i class='fa fa-envelope fa-fw'></i> "
  url = "/contact-me/"
  weight = 6
